srcpm/app/drops/forms.py
# -*- coding:utf-8 -*-

from flask_wtf import Form
from flask_wtf.file import FileField, FileAllowed, FileRequired
from wtforms import StringField, PasswordField, BooleanField, SubmitField,\
    SelectField, TextField, TextAreaField, RadioField, FileField
from wtforms import ValidationError, TextField, DateField, IntegerField
from wtforms.validators import Required, Length, Email, InputRequired, Regexp, EqualTo
from wtforms.widgets import CheckboxInput
from flask import request
from app.admin.models import Depart
from flask_pagedown.fields import PageDownField
from app.drops.models import Category

# 图片表单


class UploadImgForm(Form):
    upload = FileField(u'上传图片', validators=[
        FileRequired(),
        FileAllowed(['jpg', 'png'], 'Images only!')
    ]
    )
    submit = SubmitField('Submit')

# 搜索表单


class SearchForm(Form):
    search = StringField('search', validators=[Required(), Length(1, 20)])

# category表单


class CateForm(Form):
    catename = StringField(u'类别名', validators=[Required(), Length(1, 64)])
    submit = SubmitField(u'提交')


# drops提交表单

class DropForm(Form):
    title = StringField(u'标题', validators=[Required(), Length(
        1.50)], id='title_id')
    dropname = StringField(u'drop名', validators=[
                           Required(), Length(1.50)], id='dropname_id')
    category = RadioField(
        u'类型', coerce=int, id='category_id')
    tag = StringField(u'标签', validators=[Required(), Length(1.50)],
                      render_kw={"placeholder": u"多个tag用英文逗号隔开"})
    content = PageDownField(u'drop内容', id='content_id',validators=[Required(),Length(min=10)])
    submit = SubmitField(u'提交')

    def __init__(self, *args, **kwargs):
        super(DropForm, self).__init__(*args, **kwargs)
        self.category.choices = [(i.id, i.category_name)
                                 for i in Category.query.order_by(Category.id).all()]
# 评论表单


class CommentForm(Form):
    author_name = StringField(u'Name',validators=[
                            InputRequired(message=u"Need an name"), Length(max=50)],
                            render_kw={"placeholder": u"请输入昵称"})
    author_email = StringField(u"Email",validators=[
                             InputRequired(message=u"Need an email address"),
                             Email(message=u"Need a valid email address")],
                             render_kw={"placeholder": u"请输入邮箱"})
    content = PageDownField(u"Content")
    comt_id = IntegerField()
    submit = SubmitField(u"Save")

srcpm/app/drops/__init__.py
#-*- coding:utf-8 -*-
''' drops 蓝本文件 '''

from flask import Blueprint


drops = Blueprint('drops', __name__, static_folder='../static')

from . import views

srcpm/app/drops/views.py
# -*- coding:utf-8 -*-

from flask import render_template, flash, url_for, redirect, request, current_app, session, jsonify, abort, make_response, send_file
from flask_login import login_required, current_user, current_app, login_user
from . import drops
from .forms import CateForm, DropForm, UploadImgForm, CommentForm
from ..auth.forms import LoginForm
from ..auth.models import LoginUser
from .models import Category, Postdrop, Tag, pageby, PostQuery, Comment
from .. import db
from datetime import datetime
from ..decorators import permission_required
from random import shuffle
import re
import sys
import os
from .. import csrf


def cur_file_dir():

    path = sys.path[0]

    if os.path.isdir(path):
        return path
    elif os.path.isfile(path):
        return os.path.dirname(path)

# 过滤字符串


def str_filter(str_input):

    str_output = str_input.strip()
    str_output = str_output.replace(' ', '')
    str_output = str_output.replace('\r', '')
    str_output = str_output.replace('\n', '')
    str_output = str_output.replace(u'，', ',')
    str_output = re.sub(r"alert", '', str_output, 0, re.I)
    str_output = re.sub(r"script", '', str_output, 0, re.I)
    str_output = re.sub(r"img", '', str_output, 0, re.I)
    str_output = re.sub(r"on(.*)", '', str_output, 0, re.I)
    str_output = re.sub(r"src", '', str_output, 0, re.I)
    str_output = re.sub(r";", '', str_output, 0, re.I)
    str_output = re.sub(r"&", '', str_output, 0, re.I)
    str_output = re.sub(r"'", '', str_output, 0, re.I)
    str_output = re.sub(r'"', '', str_output, 0, re.I)
    str_output = re.sub(r"<", '', str_output, 0, re.I)
    str_output = re.sub(r">", '', str_output, 0, re.I)
    str_output = re.sub(r"/", '', str_output, 0, re.I)


    return str_output


#-----------------------上传图片----------------------------------------------

ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg', 'gif'])


def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1] in ALLOWED_EXTENSIONS


@drops.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        lg_user = LoginUser.query.filter_by(email=form.email.data).first()
        if lg_user is not None and lg_user.verify_password(form.password.data):
            login_user(lg_user, form.remember_me.data)
            # 防止任意URL跳转到其它网站
            if request.args.get('next') is not None and ('//' in request.args.get('next')):
                return redirect(url_for('main.index'))

            return redirect(request.args.get('next', url_for('drops.index')))
        flash('Invalid username or password.')
    return render_template('auth/login.html', form=form)


# 最后返回文件名

@csrf.exempt
@drops.route('/upload_img', methods=['POST'])
@permission_required('src.upload_img')
# def upload_img():
#     up_img_file = request.files['upload']
#     if up_img_file and allowed_file(up_img_file.filename):
#         img_type = up_img_file.filename.rsplit('.', 1)[1]
#         save_filename = datetime.now().strftime('%Y%m%d%H%M%s') + '.' + img_type
#         up_img_file.save(current_app.config[
#                          'UPLOAD_IMG_FOLDER'] + save_filename)
#         session['filename'] = url_for(
#             'static', filename='upload/img/' + save_filename)
#         return jsonify(result=session['filename'])
def upload_img():
    up_img_file = request.files['editormd-image-file']
    if up_img_file and allowed_file(up_img_file.filename):
        img_type = up_img_file.filename.rsplit('.', 1)[1]
        save_filename = datetime.now().strftime('%Y%m%d%H%M%s') + '.' + img_type
        up_img_file.save(current_app.config[
                         'UPLOAD_IMG_FOLDER'] + save_filename)
        session['filename'] = url_for(
            'drops.static', filename='upload/img/' + save_filename)
        s = {'success': 1, 'message': 'OK', 'url': session['filename']}
        return jsonify(s)


#--------前台展示模块---------

# 全文搜索

@drops.route('/search', methods=['GET', 'POST'])
@drops.route('/search/page/<int:pageid>', methods=['GET', 'POST'])
def search(pageid=1):
    per_page = 10
    categorys = Category.query.all()
    hot = Postdrop.query.hotdrop()[:20]
    new = Postdrop.query.newdrop()[:20]
    tag = Tag.query.all()
    shuffle(tag)
    tag = tag[:20]
    comments = Comment.query.order_by(Comment.comment_create_time.desc())[:20]
    # 第二个参数是默认书据
    searchword = request.form.get('keys', '')
    # 过滤搜索字符串
    # searchword = str_filter(searchword)
    searchword = searchword.strip()
    if not searchword:
        flash(u'没找到结果!')
        return redirect(url_for('drops.index'))

    searchresult = Postdrop.query.search(searchword)

    p = pageby(searchresult, pageid, per_page,
               Postdrop.drop_create_time.desc())

    drops = p.items
    if not p.total:
        pagination = [0]
    elif p.total % per_page:
        pagination = range(1, p.total / per_page + 2)
    else:
        pagination = range(1, p.total / per_page + 1)

    return render_template('drops/search.html',
                           key=searchword,
                           categorys=categorys,
                           drops=drops,
                           hotdrops=hot,
                           newdrops=new,
                           tags=tag,
                           comments=comments,
                           pageid=pageid,
                           pagination=pagination[pageid - 1:pageid + 10],
                           last_page=pagination[-1]
                           )


# 查询权限列表如果用户的角色和权限符合drop管理原跳转至manager页面


@drops.route('/')
@drops.route('/index')
@drops.route('/page/<int:pageid>')
def index(pageid=1):
    per_page = 10
    categorys = Category.query.all()
    p = Postdrop.query.getdrop_perpage(pageid, per_page)
    hot = Postdrop.query.hotdrop()[:20]
    new = Postdrop.query.newdrop()[:20]

    tag = Tag.query.all()
    shuffle(tag)
    tag = tag[:20]

    comments = Comment.query.order_by(Comment.comment_create_time.desc())[:20]
    drops = p.items
    if not p.total:
        pagination = [0]
    elif p.total % per_page:
        pagination = range(1, p.total / per_page + 2)
    else:
        pagination = range(1, p.total / per_page + 1)

    return render_template('drops/index.html',
                           categorys=categorys,
                           drops=drops,
                           hotdrops=hot,
                           newdrops=new,
                           tags=tag,
                           comments=comments,
                           pageid=pageid,
                           pagination=pagination[pageid - 1:pageid + 10],
                           last_page=pagination[-1],
                           nav_current="index"
                           )

# 分类目录


@drops.route('/category/<int:cateid>')
@drops.route('/category/<int:cateid>/page/<int:pageid>')
def category(cateid=1, pageid=1):
    per_page = 10
    categorys = Category.query.all()
    hot = Postdrop.query.hotdrop()[:10]
    new = Postdrop.query.newdrop()[:10]
    tag = Tag.query.all()
    shuffle(tag)
    tag = tag[:10]
    comments = Comment.query.order_by(Comment.comment_create_time.desc())[:20]

    cate = Category.query.get_or_404(cateid)

    p = pageby(cate.postdrop, pageid, per_page,
               Postdrop.drop_create_time.desc())

    drops = p.items
    if not p.total:
        pagination = [0]
    elif p.total % per_page:
        pagination = range(1, p.total / per_page + 2)
    else:
        pagination = range(1, p.total / per_page + 1)

    return render_template('drops/category.html',
                           id=cateid,
                           cate=cate,
                           categorys=categorys,
                           drops=drops,
                           hotdrops=hot,
                           newdrops=new,
                           tags=tag,
                           comments=comments,
                           pageid=pageid,
                           pagination=pagination[pageid - 1:pageid + 10],
                           last_page=pagination[-1]
                           )

# 标签目录


@drops.route('/tag/<int:tagid>')
@drops.route('/tag/<int:tagid>/page/<int:pageid>')
def tag(tagid=1, pageid=1):
    per_page = 10
    categorys = Category.query.all()
    hot = Postdrop.query.hotdrop()[:20]
    new = Postdrop.query.newdrop()[:20]
    tag = Tag.query.all()
    shuffle(tag)
    tag = tag[:20]
    comments = Comment.query.order_by(Comment.comment_create_time.desc())[:20]

    tagall = Tag.query.get_or_404(tagid)
    name = tagall.name
    p = Postdrop.query.search_tag(name)
    p = pageby(p, pageid, per_page, Postdrop.drop_create_time.desc())

    drops = p.items
    if not p.total:
        pagination = [0]
    elif p.total % per_page:
        pagination = range(1, p.total / per_page + 2)
    else:
        pagination = range(1, p.total / per_page + 1)

    return render_template('/drops/tag.html',
                           id=tagid,
                           tagall=tagall,
                           categorys=categorys,
                           drops=drops,
                           hotdrops=hot,
                           newdrops=new,
                           tags=tag,
                           comments=comments,
                           pageid=pageid,
                           pagination=pagination[pageid - 1:pageid + 10],
                           last_page=pagination[-1]
                           )


# id drop固定链接
@drops.route('/drop/<int:postid>')
def drop(postid=5):
    categorys = Category.query.all()
    hot = Postdrop.query.hotdrop()[:5]
    new = Postdrop.query.newdrop()[:5]

    tag = Tag.query.all()
    shuffle(tag)
    tag = tag[:20]
    # commentss =
    # Comment.query.order_by(Comment.comment_create_time.desc())[:20]
    drop = Postdrop.query.getall()
    shuffle(drop)
    drop = drop[:5]

    post = Postdrop.query.get_or_404(postid)

srcpm/app/templates/drops/_contenthd.html
<span style="font-size:35px;font-weight:bold;" class="glyphicon glyphicon-bookmark"><a title="{{a.drop_title}}" href="{{ url_for('drops.drop', postid=a.id) }}">{{a.drop_title}}</span>
<br>
<hr style="height:3px;border:none;border-top:3px double gray;" />
<a href="{{ url_for('drops.drop', postid=a.id) }}" class="btn btn-warning btn-sm">&nbsp;&nbsp;{{a.comment_count}}条评论&nbsp;&nbsp;</a>
|<a href="{{url_for('drops.category',cateid=a.category_id)}}" class="btn btn-warning btn-sm">&nbsp;&nbsp;{{ a.cate.category_name }}&nbsp;&nbsp;</a>
|<a href="{{ url_for('drops.tag', tagid=a.id) }}" class="btn btn-warning btn-sm">&nbsp;&nbsp;{{ a.tags_name }}&nbsp;&nbsp;</a>
<span style="float:right" class="btn btn-success btn-sm">&nbsp;&nbsp;{{ a.view_num }}人阅读&nbsp;&nbsp;</span>
<br>

srcpm/app/templates/drops/_drop.html
<ul class="posts">
{% for post in posts %}
<li class="post">
...
<div class="post-content">
...
<div class="post-footer">
<a href="{{ url_for('.drop', postid=post.id) }}">
<span class="label label-default">Permalink</span>
</a>
</div>
</div>
</li>
{% endfor %}
</ul>

srcpm/app/templates/drops/category.html
{% extends 'drops/drops_base.html' %} {% import 'bootstrap/wtf.html' as wtf %}
{% block title %} drops-分类目录 {% endblock%}
{% block page_content %}
<div class="row">

    <!-- <div class="col-md-3" style="background-color: #dedef8;box-shadow: inset 1px -1px 1px #444, inset -1px 1px 1px #444;"> -->
    <div class="col-md-3">
        {% include 'drops/_sider.html' %}
        <!--/.well -->
    </div>




    <div class="col-md-9">
        {% for a in drops%}
        <hr>
        <div class="art-{{a.id}}">
            {% include 'drops/_contenthd.html' %}
            <div class="content">
                {% if a.drop_content_html %} {% if (a.drop_content|length)>100 %} {{ (a.drop_content_html)[:200]|safe }}... {% else %} {{ (a.drop_content_html)|safe }} {% endif %} {% else %}
                <b>您输入的页面字符长度太小不予显示！</b> {% endif %}
                </code>
                </pre>
            </div>
            <div class="link">
                <p><a href="{{ url_for('drops.drop', postid=a.id) }}" style="float:right">阅读全文 &raquo;</a></p>
            </div>
            <br>
            <hr>
            <!-- <hr style=" height:2px;border:none;border-top:2px dotted #185598;" /> -->
        </div>

        {% endfor %}
        <div id="Pagination" class="pagination">
            <a href="/srcpm/drops/page/1">首页 &raquo;</a> {% for i in pagination %} {% if i==pageid %}<span class="current">{{pageid}}</span> {% else %}<a href="/srcpm/drops/page/{{i}}">{{i}}</a> {% endif %} {% endfor %}
            <span>...</span>
            <a href="/srcpm/drops/page/{{last_page}}">末页 &raquo;</a>
        </div>
    </div>


</div>
{% endblock %}

srcpm/app/templates/drops/drops.html
 {% extends 'drops/drops_base.html' %} {% import 'bootstrap/wtf.html' as wtf %}
 {% import "drops/_macros.html" as macros %} {% block title %} drops {% endblock %}
 {% block head %}
    {{ super() }}
<link rel="stylesheet" href="{{ url_for('drops.static', filename='plugins/editormd/css/editormd.preview.css') }}">
<style>
    body {
        font-family: "ff-tisa-web-pro-1", "ff-tisa-web-pro-2", "Lucida Grande", "Helvetica Neue", Helvetica, Arial, "Hiragino Sans GB", "Hiragino Sans GB W3", "Microsoft YaHei UI", "Microsoft YaHei", "WenQuanYi Micro Hei", sans-serif;
    }
</style>
<style>
    .w90 {
        width: 90%;
        margin-left: auto;
        margin-right: auto;
    }

    .w60 {
        width: 60%;
        margin-left: auto;
        margin-right: auto;
    }

    .w35 {
        width: 35%;
        margin-left: auto;
        margin-right: auto;
    }
</style>
<style>
    #sidebar {
        width: 400px;
        height: 100%;
        position: fixed;
        top: 0;
        right: 0;
        overflow: hidden;
        background: #fff;
        z-index: 100;
        padding: 18px;
        border: 1px solid #ddd;
        border-top: none;
        border-bottom: none;
    }

    #sidebar:hover {
        overflow: auto;
    }

    #sidebar h1 {
        font-size: 16px;
    }

    #custom-toc-container {
        padding-left: 0;
    }

    /*#test-editormd-view,
    #test-editormd-view2 {
        padding-left: 0;
        padding-right: 430px;
        margin: 0;
    }*/
</style>

{% endblock %} {% block page_content %}
<header>
    <span style="font-size:30px;font-weight:bold;color:#6495ED;">*{{post.drop_title}}</span>
</header>
<hr>
<div class="container w90">
    <b>
            <p class="title_info">&nbsp;&nbsp;
            作者:<span class="info_author">{{authorname.username}}</span>&nbsp;&nbsp;
            更新时间：<span class="info_date">{{moment(post.drop_modified_time).format('YYYY年M月D日, H:mm:ss')}}</span>&nbsp;&nbsp;
            阅读次数：<span class="info_times">{{post.view_num}}</span>&nbsp;&nbsp;
            评论：<span class="info_commments">{{post.comment_count}}</span>&nbsp;&nbsp;
            标签:<span>{{post.tags_name}}</span>&nbsp;&nbsp;
            </p>
        </b>
    <hr>
</div>
<div class="container w90">
    <div id="layout">
        <!-- <div id="sidebar">
            <h1>目录</h1>
            <div class="markdown-body editormd-preview-container" id="custom-toc-container">#custom-toc-container</div>
        </div> -->
        <br>
        <div id="test-editormd-view">
            <textarea style="display:none;" name="test-editormd-markdown-doc">{{ post.drop_content }}</textarea>
        </div>
        <br>
        <hr>
        <div id="test-editormd-view2">
            <textarea id="append-test" style="display:none; w90"></textarea>
        </div>
    </div>
</div>

<div class="container w90">
    <ol class="commentlist">
        {% for c in postcoments %}
        <li id="li-comment-{{c.id}}" class="comment even thread-even depth-1">
            <article id="comment-{{c.id}}" class="comment">
                <footer class="clearfix comment-head">
                    昵称:<span style="font-size:16px;font-weight:bold;">&nbsp;&nbsp;{{c.author_name}}&nbsp;&nbsp;</span>
                    <div class="comment-meta commentmetadata">
                        <a href="#comments">
                            <time datetime="2013-01-01T02:07:46+00:00" pubdate=""> {{moment(c.comment_create_time).format('YYYY年M月D日, H:mm:ss')}} </time>
                        </a>
                    </div>
                </footer>
                <div class="comment-content">
                    <p>{{c.content_html|safe}}</p>
                </div>
                <div class="act">
                    <!--  留空追加回复-->
                </div>
                <hr>
            </article>
        </li>
        {% endfor %}
    </ol>
    <form action="{{url_for('drops.addcomment')}}" method="post" class="form-inline" role="form">

        <div style="display:none;">
            {{ form.hidden_tag() }} {{ form.comt_id(type='hidden', value=post.id)}}
        </div>
        <div class=form-group>
            <span style="font-size:16px;font-weight:bold;">Name：</span>{{ form.author_name.label(class="sr-only") }}{{ form.author_name(class="form-control" ) }}
        </div>
        <div class=form-group>
            <span style="font-size:16px;font-weight:bold;">Email：</span>{{ form.author_email.label(class="sr-only") }}{{ form.author_email(class="form-control" ) }}
        </div>

        <div class=form-group>
            {{ form.content.label(class="control-label") }}{{ form.content(rows = 3, cols = 100) }}
        </div>
        <br>
        <div class=form-group>
            {{ form.submit(class="btn btn-default") }}
        </div>

    </form>
</div>

<script src="{{ url_for('drops.static', filename='jquery.min.js') }}"></script>
<script src="{{ url_for('drops.static', filename='plugins/editormd/lib/marked.min.js') }}"></script>
<script src="{{ url_for('drops.static', filename='plugins/editormd/lib/prettify.min.js') }}"></script>
<script src="{{ url_for('drops.static', filename='plugins/editormd/lib/raphael.min.js') }}"></script>
<script src="{{ url_for('drops.static', filename='plugins/editormd/lib/underscore.min.js') }}"></script>
<script src="{{ url_for('drops.static', filename='plugins/editormd/lib/sequence-diagram.min.js') }}"></script>
<script src="{{ url_for('drops.static', filename='plugins/editormd/lib/flowchart.min.js') }}"></script>
<script src="{{ url_for('drops.static', filename='plugins/editormd/lib/jquery.flowchart.min.js') }}"></script>

<script src="{{ url_for('drops.static', filename='plugins/editormd/editormd.js') }}"></script>
<script type="text/javascript">
    $(function() {
        var testEditormdView, testEditormdView2;
        // $.get("{{ url_for('drops.downdrops',postid=post.id)}}", function(markdown) {
        //
        //
        //     testEditormdView = editormd.markdownToHTML("test-editormd-view", {
        //         markdown: markdown, //+ "\r\n" + $("#append-test").text(),
        //         //htmlDecode      : true,       // 开启 HTML 标签解析，为了安全性，默认不开启
        //         htmlDecode: "style,script,iframe", // you can filter tags decode
        //         //toc             : false,
        //         tocm: true, // Using [TOCM]
        //         tocContainer: "#custom-toc-container", // 自定义 ToC 容器层
        //         //gfm             : false,
        //         //tocDropdown     : true,
        //         // markdownSourceCode : true, // 是否保留 Markdown 源码，即是否删除保存源码的 Textarea 标签
        //         emoji: true,
        //         taskList: true,
        //         tex: true, // 默认不解析
        //         flowChart: true, // 默认不解析
        //         sequenceDiagram: true, // 默认不解析
        //     });
        //
        //     //console.log("返回一个 jQuery 实例 =>", testEditormdView);
        //
        //     // 获取Markdown源码
        //     //console.log(testEditormdView.getMarkdown());
        //
        //     //alert(testEditormdView.getMarkdown());
        // });

        testEditormdView = editormd.markdownToHTML("test-editormd-view", {
            htmlDecode: "style,script,iframe", // you can filter tags decode
            //toc             : false,
            //tocm: true, // Using [TOCM]
            //tocContainer: "#custom-toc-container", // 自定义 ToC 容器层
            gfm : true,
            //tocDropdown     : true,
            // markdownSourceCode : true, // 是否保留 Markdown 源码，即是否删除保存源码的 Textarea 标签
            //emoji: true,
            taskList: true,
            //tex: true, // 默认不解析
            flowChart: true, // 默认不解析
            sequenceDiagram: true, // 默认不解析
        });
    });
</script>
{% endblock %}

srcpm/app/templates/drops/index.html
{% extends 'drops/drops_base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block title %} drops-首页 {% endblock%}
{% block page_content %}
<div class="row">

    <!-- <div class="col-md-3" style="background-color: #dedef8;box-shadow: inset 1px -1px 1px #444, inset -1px 1px 1px #444;"> -->
    <div class="col-md-3">
        {% include 'drops/_sider.html' %}


    </div>




    <div class="col-md-9">
        {% for a in drops%}

        <div class="art-{{a.id}}">
            {% include 'drops/_contenthd.html' %}
            <br>
            <div class="content">

                {% if a.drop_content_html %} {% if (a.drop_content|length)>100 %} {{ (a.drop_content_html)[:200]|safe }}... {% else %} {{ (a.drop_content_html)|safe }} {% endif %} {% else %}
                <b>您输入的页面字符长度太小不予显示！</b> {% endif %}
                </code>
                </pre>
            </div>
            <div class="link">
                <p><a href="{{ url_for('drops.drop', postid=a.id) }}" style="float:right">阅读全文 &raquo;</a></p>
            </div>
            <br>
            <hr>
            <!-- <hr style=" height:2px;border:none;border-top:2px dotted #185598;" /> -->
        </div>

        {% endfor %}
        <div  class="pagination">
            <a href="/srcpm/drops/page/1">首页 &raquo;</a>
            {% for i in pagination %}
            {% if i==pageid %}
            <span class="current">
            {{pageid}}
            </span>
            {% else %}
            <a href="/srcpm/drops/page/{{i}}">{{i}}</a>
            {% endif %}
            {% endfor %}
            <span>...</span>
            <a href="/srcpm/drops/page/{{last_page}}">末页 &raquo;</a>
        </div>
    </div>


</div>
{% endblock %}

srcpm/app/templates/drops/manager.html
{% extends 'drops/drops_base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %} drops {% endblock%}

srcpm/app/templates/drops/newcate.html
{% extends 'drops/drops_base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block title%} drops-新建 {% endblock%}
{% block page_content %}
<div class="page-header">
    <h1>新建分类</h1>
</div>

<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

srcpm/app/templates/drops/search.html
{% extends 'drops/drops_base.html' %} {% import 'bootstrap/wtf.html' as wtf %} {% block title %} drops-首页 {% endblock%} {% block page_content %}
<div class="row">

    <!-- <div class="col-md-3" style="background-color: #dedef8;box-shadow: inset 1px -1px 1px #444, inset -1px 1px 1px #444;"> -->
    <div class="col-md-3">
        {% include 'drops/_sider.html' %}


    </div>




    <div class="col-md-9">
        {% for a in drops%}

        <div class="art-{{a.id}}">
            {% include 'drops/_contenthd.html' %}
            <br>
            <div class="content">

                {% if a.drop_content_html %} {% if (a.drop_content|length)>100 %} {{ (a.drop_content_html)[:200]|safe }}... {% else %} {{ (a.drop_content_html)|safe }} {% endif %} {% else %}
                <b>您输入的页面字符长度太小不予显示！</b> {% endif %}
                </code>
                </pre>
                <p><a href="{{ url_for('drops.drop', postid=a.id) }}" style="float:right">阅读全文 &raquo;</a></p>
            </div>
            <br>
            <hr>
            <!-- <hr style=" height:2px;border:none;border-top:2px dotted #185598;" /> -->
        </div>

        {% endfor %}
        <div id="Pagination" class="pagination">
            <a href="/srcpm/drops/page/1">首页 &raquo;</a>
            {% for i in pagination %}
            {% if i==pageid %}
            <span class="current">
            {{pageid}}
            </span>
            {% else %}
            <a href="/srcpm/drops/page/{{i}}">{{i}}</a>
            {% endif %}
            {% endfor %}
            <span>...</span>
            <a href="/srcpm/drops/page/{{last_page}}">末页 &raquo;</a>
        </div>
    </div>


</div>
{% endblock %}